CREATE table app_user (
       id int4 generated by default as identity,
        email varchar(255) not null,
        password varchar(255),
        username varchar(255) not null,
        primary key (id)
    );

CREATE table app_user_app_user_roles (
       app_user_id int4 not null,
        app_user_roles int4
    );
alter table if exists app_user 
       drop constraint if exists UK_1j9d9a06i600gd43uu3km82jw;

alter table if exists app_user 
       add constraint UK_1j9d9a06i600gd43uu3km82jw unique (email);

alter table if exists app_user 
       drop constraint if exists UK_3k4cplvh82srueuttfkwnylq0;

alter table if exists app_user 
       add constraint UK_3k4cplvh82srueuttfkwnylq0 unique (username);

alter table if exists app_user_app_user_roles 
       add constraint FK8e2v1rmbd8nee9vje8qbgb83n 
       foreign key (app_user_id) 
       references app_user;
